spring:
  application:
    name: server

server:
  port: 8080

gemini:
  api-key: AIzaSyB1SAIkjBdG3I1137JFfFa1iRag48c0G4M
  base-url: https://generativelanguage.googleapis.com
  model: gemini-2.5-flash