spring:
  application:
    name: server

server:
  port: 8080
  forward-headers-strategy: framework

gemini:
  api-key: ${GEMINI_API_KEY}
  base-url: https://generativelanguage.googleapis.com
  model: gemini-2.5-flash

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha